package com.gafipro.gafileds.command;

import com.gafipro.gafileds.GafiLeds;
import com.gafipro.gafileds.config.GafiLedsConfig;
import com.gafipro.gafileds.govee.GoveeDevice;
import com.gafipro.gafileds.govee.GoveeStatus;
import com.gafipro.gafileds.reactive.RgbColor;
import com.gafipro.gafileds.reactive.ReactiveConfig;
import com.mojang.brigadier.LiteralMessage;
import com.mojang.brigadier.arguments.StringArgumentType;
import com.mojang.brigadier.builder.LiteralArgumentBuilder;
import com.mojang.brigadier.suggestion.SuggestionProvider;
import net.fabricmc.fabric.api.client.command.v2.ClientCommandManager;
import net.fabricmc.fabric.api.client.command.v2.ClientCommandRegistrationCallback;
import net.fabricmc.fabric.api.client.command.v2.FabricClientCommandSource;
import net.minecraft.text.Text;
import java.net.InetAddress;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.CompletableFuture;
import static com.mojang.brigadier.arguments.IntegerArgumentType.integer;

public final class GoveeCommands {
    private GoveeCommands(){}
    public static void register(GafiLeds mod){ClientCommandRegistrationCallback.EVENT.register((dispatcher,registryAccess)->dispatcher.register(build(mod)));}
    private static LiteralArgumentBuilder<FabricClientCommandSource> build(GafiLeds mod){var root=ClientCommandManager.literal("govee");
        root.then(ClientCommandManager.literal("scan").executes(c->{var source=c.getSource();source.sendFeedback(Text.literal("[GafiLeds] Scanning the LAN for Govee devices..."));mod.discovery().scanAsync().whenComplete((devices,error)->source.getClient().execute(()->{if(error!=null){source.sendError(Text.literal("[GafiLeds] Discovery failed: "+message(error)));return;}if(devices==null||devices.isEmpty()){source.sendFeedback(Text.literal("[GafiLeds] No Govee LAN devices found."));return;}source.sendFeedback(Text.literal("[GafiLeds] Found "+devices.size()+" device(s):"));for(int i=0;i<devices.size();i++){GoveeDevice d=devices.get(i);source.sendFeedback(Text.literal(String.format(Locale.ROOT,"  %d. %s (%s) - %s",i+1,d.model(),d.name(),d.address().getHostAddress())));}}));return 1;}));
        root.then(ClientCommandManager.literal("device").then(ClientCommandManager.literal("list").executes(c->listDevices(mod,c.getSource()))).then(ClientCommandManager.literal("select").then(ClientCommandManager.argument("device",StringArgumentType.word()).suggests(deviceSuggestions(mod)).executes(c->selectDevice(mod,c.getSource(),StringArgumentType.getString(c,"device"))))));
        root.then(ClientCommandManager.literal("status").executes(c->status(mod,c.getSource())));
        root.then(ClientCommandManager.literal("on").executes(c->{GoveeDevice d=selectedDevice(mod);if(d==null)return error(c.getSource(),"No Govee device selected.");mod.commandScheduler().sendOn(d.address(),true);feedback(c.getSource(),"Sent ON to "+d.model()+" @ "+d.address().getHostAddress());return 1;}));
        root.then(ClientCommandManager.literal("off").executes(c->{GoveeDevice d=selectedDevice(mod);if(d==null)return error(c.getSource(),"No Govee device selected.");mod.commandScheduler().sendOn(d.address(),false);feedback(c.getSource(),"Sent OFF to "+d.model()+" @ "+d.address().getHostAddress());return 1;}));
        root.then(ClientCommandManager.literal("color").then(ClientCommandManager.argument("hex",StringArgumentType.greedyString()).suggests((ctx,b)->{b.suggest("#FF0000");b.suggest("#00FF00");b.suggest("#0000FF");b.suggest("#FFFFFF");b.suggest("#FF8800");return b.buildFuture();}).executes(c->{GoveeDevice d=selectedDevice(mod);if(d==null)return error(c.getSource(),"No Govee device selected.");try{String raw=StringArgumentType.getString(c,"hex").trim();RgbColor color=RgbColor.parseHex(raw);mod.commandScheduler().sendColorImmediate(d.address(),color);feedback(c.getSource(),"Sent "+color.toHex()+" to "+d.model());return 1;}catch(IllegalArgumentException e){return error(c.getSource(),e.getMessage());}})));
        root.then(ClientCommandManager.literal("brightness").then(ClientCommandManager.argument("value",integer(1,100)).executes(c->{GoveeDevice d=selectedDevice(mod);if(d==null)return error(c.getSource(),"No Govee device selected.");int v=com.mojang.brigadier.arguments.IntegerArgumentType.getInteger(c,"value");mod.configManager().update(mod.configManager().get().withBrightness(v));mod.commandScheduler().sendBrightness(d.address(),v);feedback(c.getSource(),"Brightness set to "+v+"%.");return 1;})));
        var reactive=ClientCommandManager.literal("reactive");reactive.executes(c->toggleReactive(mod,c.getSource()));reactive.then(ClientCommandManager.literal("on").executes(c->enableReactive(mod,c.getSource())));reactive.then(ClientCommandManager.literal("off").executes(c->disableReactive(mod,c.getSource())));reactive.then(ClientCommandManager.literal("status").executes(c->reactiveStatus(mod,c.getSource())));reactive.then(ClientCommandManager.literal("smooth").then(ClientCommandManager.argument("value",StringArgumentType.word()).executes(c->setSmooth(mod,c.getSource(),StringArgumentType.getString(c,"value")))));reactive.then(ClientCommandManager.literal("threshold").then(ClientCommandManager.argument("value",StringArgumentType.word()).executes(c->setThreshold(mod,c.getSource(),StringArgumentType.getString(c,"value")))));reactive.then(ClientCommandManager.literal("fps").then(ClientCommandManager.argument("value",integer(1,30)).executes(c->setReactiveFps(mod,c.getSource(),com.mojang.brigadier.arguments.IntegerArgumentType.getInteger(c,"value")))));reactive.then(ClientCommandManager.literal("segments").executes(c->error(c.getSource(),"Segment reactive is reserved for a future model-specific protocol implementation.")));root.then(reactive);
        root.then(ClientCommandManager.literal("reload").executes(c->{mod.reloadConfig();feedback(c.getSource(),"Configuration reloaded.");return 1;}));return root;}
    private static SuggestionProvider<FabricClientCommandSource> deviceSuggestions(GafiLeds mod){return (ctx,b)->{for(int i=0;i<mod.discovery().lastResults().size();i++){GoveeDevice d=mod.discovery().lastResults().get(i);b.suggest(Integer.toString(i+1),new LiteralMessage(d.model()+" - "+d.address().getHostAddress()));b.suggest(d.address().getHostAddress(),new LiteralMessage(d.model()));}return b.buildFuture();};}
    private static int selectDevice(GafiLeds mod,FabricClientCommandSource source,String selector){GoveeDevice chosen=null;List<GoveeDevice> ds=mod.discovery().lastResults();try{int i=Integer.parseInt(selector)-1;if(i>=0&&i<ds.size())chosen=ds.get(i);}catch(NumberFormatException ignored){}if(chosen==null)for(GoveeDevice d:ds)if(d.address().getHostAddress().equalsIgnoreCase(selector)||d.id().equalsIgnoreCase(selector)){chosen=d;break;}if(chosen==null)return error(source,"Unknown device. Run /govee scan first.");mod.configManager().update(mod.configManager().get().withSelectedDevice(chosen.id(),chosen.address().getHostAddress(),chosen.model()));feedback(source,"Selected "+chosen.model()+" ("+chosen.address().getHostAddress()+").");return 1;}
    private static int listDevices(GafiLeds mod,FabricClientCommandSource source){List<GoveeDevice> ds=mod.discovery().lastResults();if(ds.isEmpty())return error(source,"No discovered devices. Run /govee scan.");for(int i=0;i<ds.size();i++){GoveeDevice d=ds.get(i);feedback(source,String.format(Locale.ROOT,"%d. %s - %s (%s)",i+1,d.model(),d.address().getHostAddress(),d.name()));}return 1;}
    private static int status(GafiLeds mod,FabricClientCommandSource source){GafiLedsConfig cfg=mod.configManager().get();feedback(source,"Device: "+(cfg.selectedDeviceIp().isBlank()?"none":cfg.selectedDeviceModel()+" @ "+cfg.selectedDeviceIp()));feedback(source,"Brightness: "+cfg.brightness()+"% | Reactive: "+mod.reactiveController().state());if(!cfg.selectedDeviceIp().isBlank())try{InetAddress a=InetAddress.getByName(cfg.selectedDeviceIp());CompletableFuture.supplyAsync(()->mod.goveeClient().requestStatus(a)).thenAccept(r->source.getClient().execute(()->{if(r.isPresent()){GoveeStatus s=r.get();feedback(source,"LAN status: "+(s.onOff()!=null&&s.onOff()==1?"ON":"OFF")+" | brightness="+s.brightness()+" | color="+(s.color()==null?"unknown":s.color().toHex()));}else feedback(source,"LAN status: no response (device may still accept fire-and-forget commands).");}));}catch(Exception e){return error(source,"Invalid configured IP: "+cfg.selectedDeviceIp());}return 1;}
    private static int toggleReactive(GafiLeds mod,FabricClientCommandSource s){return mod.reactiveController().isRunning()?disableReactive(mod,s):enableReactive(mod,s);}
    private static int enableReactive(GafiLeds mod,FabricClientCommandSource s){if(mod.configManager().get().selectedDeviceIp().isBlank())return error(s,"Select a device first with /govee scan and /govee device select <device>.");if(!mod.reactiveController().start())return error(s,"Reactive failed to start: "+mod.reactiveController().lastError());feedback(s,"Reactive mode enabled.");return 1;}
    private static int disableReactive(GafiLeds mod,FabricClientCommandSource s){mod.reactiveController().stop();feedback(s,"Reactive mode disabled.");return 1;}
    private static int reactiveStatus(GafiLeds mod,FabricClientCommandSource s){var r=mod.reactiveController();var m=r.metrics();feedback(s,"Reactive: "+r.state()+" | capture="+String.format(Locale.ROOT,"%.1f",m.captureFps())+" fps | analysis="+String.format(Locale.ROOT,"%.1f",m.analysisFps())+" fps | updates="+String.format(Locale.ROOT,"%.1f",m.updateFps())+"/s");feedback(s,"Observed="+hex(m.observed())+" Target="+hex(m.target())+" Current="+hex(m.current()));feedback(s,"Sent="+m.sentCount()+" | dropped="+m.droppedFrames()+" | errors="+m.errors());if(!r.lastError().isBlank())feedback(s,"Last error: "+r.lastError());return 1;}
    private static int setSmooth(GafiLeds mod,FabricClientCommandSource s,String raw){try{double v=Double.parseDouble(raw);GafiLedsConfig cfg=mod.configManager().get();ReactiveConfig r=cfg.reactive();mod.configManager().update(cfg.withReactive(new ReactiveConfig(r.enabled(),r.captureFps(),r.analysisFps(),r.updateFps(),r.sampleWidth(),r.sampleHeight(),v,r.threshold(),r.darkThreshold(),r.saturationWeight(),r.brightnessWeight(),r.followMinecraftMonitor(),r.monitorIndex(),r.darkScenesReduceBrightness())));mod.reloadConfig();feedback(s,"Reactive smoothing set to "+v+".");return 1;}catch(NumberFormatException e){return error(s,"Smoothing must be a number between 0.01 and 1.0.");}}
    private static int setThreshold(GafiLeds mod,FabricClientCommandSource s,String raw){try{double v=Double.parseDouble(raw);GafiLedsConfig cfg=mod.configManager().get();ReactiveConfig r=cfg.reactive();mod.configManager().update(cfg.withReactive(new ReactiveConfig(r.enabled(),r.captureFps(),r.analysisFps(),r.updateFps(),r.sampleWidth(),r.sampleHeight(),r.smoothing(),v,r.darkThreshold(),r.saturationWeight(),r.brightnessWeight(),r.followMinecraftMonitor(),r.monitorIndex(),r.darkScenesReduceBrightness())));mod.reloadConfig();feedback(s,"Reactive threshold set to "+v+".");return 1;}catch(NumberFormatException e){return error(s,"Threshold must be a number between 0.0 and 1.0.");}}
    private static int setReactiveFps(GafiLeds mod,FabricClientCommandSource s,int v){GafiLedsConfig cfg=mod.configManager().get();ReactiveConfig r=cfg.reactive();ReactiveConfig u=new ReactiveConfig(r.enabled(),Math.min(r.captureFps(),v),Math.min(r.analysisFps(),v),v,r.sampleWidth(),r.sampleHeight(),r.smoothing(),r.threshold(),r.darkThreshold(),r.saturationWeight(),r.brightnessWeight(),r.followMinecraftMonitor(),r.monitorIndex(),r.darkScenesReduceBrightness());mod.configManager().update(cfg.withReactive(u));mod.reloadConfig();feedback(s,"Reactive FPS limits set to "+v+".");return 1;}
    private static GoveeDevice selectedDevice(GafiLeds mod){GafiLedsConfig cfg=mod.configManager().get();if(cfg.selectedDeviceIp().isBlank())return null;for(GoveeDevice d:mod.discovery().lastResults())if(d.address().getHostAddress().equalsIgnoreCase(cfg.selectedDeviceIp()))return d;try{return new GoveeDevice(cfg.selectedDeviceId(),cfg.selectedDeviceModel(),cfg.selectedDeviceModel(),InetAddress.getByName(cfg.selectedDeviceIp()));}catch(Exception e){return null;}}
    private static int error(FabricClientCommandSource s,String m){s.sendError(Text.literal("[GafiLeds] "+m));return 0;}private static void feedback(FabricClientCommandSource s,String m){s.sendFeedback(Text.literal("[GafiLeds] "+m));}private static String hex(RgbColor c){return c==null?"-":c.toHex();}private static String message(Throwable e){Throwable t=e;while(t.getCause()!=null&&(t.getMessage()==null||t.getMessage().isBlank()))t=t.getCause();return t.getMessage()==null?t.getClass().getSimpleName():t.getMessage();}
}
